spring:
  datasource:
    datasource:
    url: jdbc:mysql://localhost:3306/db_webproject
    username: webprojectuser
    password: webprojectpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
